steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/round-folio-468620-j8/magicsell-v2-staging:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/round-folio-468620-j8/magicsell-v2-staging:latest'
      - '.'
    timeout: 1200s

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/round-folio-468620-j8/magicsell-v2-staging:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/round-folio-468620-j8/magicsell-v2-staging:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'magicsell-v2-staging'
      - '--image'
      - 'gcr.io/round-folio-468620-j8/magicsell-v2-staging:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,APP_ENVIRONMENT_NAME=STAGING'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--port'
      - '8080'

images:
  - 'gcr.io/round-folio-468620-j8/magicsell-v2-staging:$COMMIT_SHA'
  - 'gcr.io/round-folio-468620-j8/magicsell-v2-staging:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
