# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f2591d0ad2569399d9bd47dada275546"
name = "magicsell v2"
application_url = "https://tunnel.magicsell.ai/"
embedded = true
handle = "magicshift-v2"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2024-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_product_listings,read_publications,read_themes,write_customers,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://staging.magicsell.ai/auth/callback",
  "https://staging.magicsell.ai/auth/shopify/callback",
  "https://staging.magicsell.ai/api/auth/callback"
]

[pos]
embedded = false
