# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3169c085334a859c018b427ed10581b7"
name = "Upsell & Cross Sell MagicSell"
application_url = "https://api.magicsell.ai/"
embedded = true
handle = "magicshift"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/order/create"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_product_listings,read_publications,read_themes,write_customers,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://api.magicsell.ai/auth/callback",
  "https://api.magicsell.ai/auth/shopify/callback",
  "https://api.magicsell.ai/api/auth/callback"
]

[pos]
embedded = false
